name: Test Deezer Extractor

on:
  workflow_dispatch:
    inputs:
      deezer_url:
        description: "Enlace de Deezer (track o album)"
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v6

      - name: Mostrar archivo del extractor
        run: |
          echo "========================================"
          echo "DEEZE​R EXTRACTOR"
          echo "========================================"
          sed -n '1,300p' deezer_extractor.py

      - name: Instalar dependencia
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Ejecutar extractor
        run: |
          echo "========================================"
          echo "URL DE PRUEBA"
          echo "========================================"
          echo "${{ inputs.deezer_url }}"

          echo ""
          echo "========================================"
          echo "RESULTADO"
          echo "========================================"

          python deezer_extractor.py "${{ inputs.deezer_url }}"