name: Test Deezer Extractor

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v6

      - name: Verificar archivos
        run: |
          echo "========================================"
          echo "ARCHIVOS DEL REPOSITORIO"
          echo "========================================"
          ls -la

          echo ""
          echo "========================================"
          echo "DEEZE​R_EXTRACTOR.PY"
          echo "========================================"
          pwd
          find . -name "deezer_extractor.py" -type f -print

          echo ""
          echo "========================================"
          echo "PRIMERAS 250 LINEAS DEL EXTRACTOR"
          echo "========================================"
          sed -n '1,250p' deezer_extractor.py

      - name: Instalar dependencia
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Ejecutar extractor
        run: |
          python deezer_extractor.py "https://www.deezer.com/album/1110543002"